baseURL = 'https://nithwith.github.io/blog/'
title = 'Mon blog'
theme = "hugo-theme-stack"
description = "CYCLING / TRAVEL / DIY"

languageCode = 'fr-fr'
defaultContentLanguage = "fr-fr"

ignoreLogs = ['warning-goldmark-raw-html']

[markup.goldmark.renderer]
unsafe = true
enableEmoji = true

[menu]
[[menu.main]]
    name = "Accueil"
    url = "/"
    weight = -100
[[menu.main]]
    name = 'Aventures'
    url = '/tags/aventure/'
    weight = -100
[[menu.main]]
    name = 'Heatmap'
    url = '/carte-de-mes-voyages'
    weight = -100


